USE OnePageAssessment
GO


TRUNCATE TABLE tblApplicant_Input
TRUNCATE TABLE tblApplicantTab_Input
TRUNCATE TABLE tblAssetAndLiabilityTab_Input
TRUNCATE TABLE tblConditionTab_Input
TRUNCATE TABLE tblCreditHistoryTab_Input
TRUNCATE TABLE tblDecisionSummaryTab_Input
TRUNCATE TABLE tblExceptionTab_Input
TRUNCATE TABLE tblExitStrategyTab_Input
TRUNCATE TABLE tblIncomeTab_Input
TRUNCATE TABLE tblLivingExpenseTab_Input
TRUNCATE TABLE tblResponsibleLendingTab_Input
TRUNCATE TABLE tblSecurityTab_Input
TRUNCATE TABLE tblServicingTab_Input
TRUNCATE TABLE tblTransactionTab_Input